global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "postgresql"
    static_configs:
      - targets: [ "postgres-exporter:9187" ]

  - job_name: "redis"
    static_configs:
      - targets: [ "redis-exporter:9121" ]

  - job_name: "kafka"
    static_configs:
      - targets: [ "kafka-exporter:9308" ]

  - job_name: "producer"
    static_configs:
      - targets: [ "producer:8080" ]

  - job_name: "consumer"
    static_configs:
      - targets: [ "consumer:8081" ]

